server:
  port: 8001

#mybatis 配置
mybatis:
  type-aliases-package: com.nb.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: on

#spring 配置
spring:
  application:
    name: springcloud-proder-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://139.196.112.185:3306/DB01?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456